version: '3'



services:

  sleek-airflow:

    image: n3teste:latest

    

    volumes:

      - ./airflow:/opt/airflow



    ports:

      - "8080:8080"



    command: airflow standalone

  sleek-smtp:
    image: bytemark/smtp
    restart: always
